# Load Libraries

In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

In [146]:
tf.__version__

'2.8.0'

In [147]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [148]:
A = 5
B = 8

result = (2*A + 3*B )

print(result)
print(type(result))


34
<class 'int'>


In [149]:
A = np.array([1,2,2,2,3,5])
B = np.array([1,2,2,2,3,5])

result = (2*A + 3*B )

print(result)
print(type(result))


[ 5 10 10 10 15 25]
<class 'numpy.ndarray'>


In [150]:
A = tf.constant([1,2,2,2,3,5])
B = tf.constant([1,2,2,2,3,5])

result = (2*A + 3*B ) **2

print(result)
print(type(result))


tf.Tensor([ 25 100 100 100 225 625], shape=(6,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [151]:
type(result.numpy())

numpy.ndarray

In [152]:
income_data = pd.read_csv('adult.csv', sep=',',engine='python' )
income_data.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num','marital-status','occupation','relationship', 'race', 'sex', 'capital-gain', 'capital-loss','hours-per-week', 'native-country' , 'income_class']

In [153]:
income_data

age     workclass  fnlwgt     education  education-num  \
0       25       Private  226802          11th              7   
1       38       Private   89814       HS-grad              9   
2       28     Local-gov  336951    Assoc-acdm             12   
3       44       Private  160323  Some-college             10   
4       18             ?  103497  Some-college             10   
...    ...           ...     ...           ...            ...   
48837   27       Private  257302    Assoc-acdm             12   
48838   40       Private  154374       HS-grad              9   
48839   58       Private  151910       HS-grad              9   
48840   22       Private  201490       HS-grad              9   
48841   52  Self-emp-inc  287927       HS-grad              9   

           marital-status         occupation relationship   race     sex  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income_class  
0                 0             0              40  United-States        <=50K  
1                 0             0              50  United-States        <=50K  
2                 0             0              40  United-States         >50K  
3              7688             0              40  United-States         >50K  
4                 0             0              30  United-States        <=50K  
...             ...           ...             ...            ...          ...  
48837             0             0              38  United-States        <=50K  
48838             0             0              40  United-States         >50K  
48839             0             0              40  United-States        <=50K  
48840             0             0              20  United-States        <=50K  
48841         15024             0              40  United-States         >50K  

[48842 rows x 15 columns]

In [154]:
income_attributes = income_data.drop(columns = ["income_class"])
income_target = income_data.income_class

In [155]:
income_attributes = pd.get_dummies(income_attributes)

In [156]:
income_target = income_target.replace({"<=50K":0 , ">50K" : 1})

In [157]:
income_attributes = income_attributes.drop(columns = ['fnlwgt'])

In [158]:
income_target.value_counts()

0    37155
1    11687
Name: income_class, dtype: int64

In [159]:
income_attributes_train, income_attributes_test, income_target_train, income_target_test= train_test_split(
    income_attributes,
    income_target,
    test_size= 5000,
    random_state= 33,
    stratify= income_target)

check the stratificatons

In [160]:
income_target_train.value_counts()/ len(income_target_train)

0    0.760709
1    0.239291
Name: income_class, dtype: float64

In [161]:
income_target_test.value_counts()/ len(income_target_test)

0    0.7608
1    0.2392
Name: income_class, dtype: float64

In [162]:
income_attributes_train.values

array([[21, 10,  0, ...,  1,  0,  0],
       [46, 13,  0, ...,  1,  0,  0],
       [25, 11,  0, ...,  1,  0,  0],
       ...,
       [35, 10,  0, ...,  1,  0,  0],
       [23, 10,  0, ...,  0,  0,  0],
       [47,  9,  0, ...,  1,  0,  0]], dtype=int64)

In [163]:
scaler = MinMaxScaler()
income_attributes_train_scaled = scaler.fit_transform(income_attributes_train)
income_attributes_test_scaled = scaler.fit_transform(income_attributes_test)

In [164]:
income_attributes_train_scaled.max()

1.0

In [165]:
num_atrributes = income_attributes.shape[1]
num_atrributes

107

In [166]:
log_regression = Sequential(
    [
        Input(shape = (num_atrributes,)),
        Dense(1,activation = 'sigmoid')
    ], name = 'log_reg')

In [167]:
log_regression.summary()

Model: "log_reg"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 108       
                                                                 
Total params: 108
Trainable params: 108
Non-trainable params: 0
_________________________________________________________________


In [174]:
log_regression.compile(loss = 'binary_crossentropy', optimizer = 'adam')

In [175]:
log_regression.fit(
    income_attributes_train,
    income_target_train,
    epochs = 99,
    batch_size =len(income_attributes_train)
)

Epoch 1/99
1/1 [==============================] - 0s 411ms/step - loss: 275.4702
Epoch 2/99
1/1 [==============================] - 0s 34ms/step - loss: 275.2953
Epoch 3/99
1/1 [==============================] - 0s 30ms/step - loss: 275.1205
Epoch 4/99
1/1 [==============================] - 0s 26ms/step - loss: 274.9456
Epoch 5/99
1/1 [==============================] - 0s 40ms/step - loss: 274.7708
Epoch 6/99
1/1 [==============================] - 0s 41ms/step - loss: 274.5959
Epoch 7/99
1/1 [==============================] - 0s 30ms/step - loss: 274.4210
Epoch 8/99
1/1 [==============================] - 0s 26ms/step - loss: 274.2462
Epoch 9/99
1/1 [==============================] - 0s 29ms/step - loss: 274.0713
Epoch 10/99
1/1 [==============================] - 0s 27ms/step - loss: 273.8965
Epoch 11/99
1/1 [==============================] - 0s 31ms/step - loss: 273.7216
Epoch 12/99
1/1 [==============================] - 0s 28ms/step - loss: 273.5468
Epoch 13/99
1/1 [===================

In [176]:
nn = Sequential([
    Input(shape = (num_atrributes,)),
    Dense(30,activation = 'relu'),
    Dense(20,activation = 'relu'),
    Dense(10,activation = 'relu'),
    Dense(1,activation = 'sigmoid')
])

In [178]:
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 30)                3240      
                                                                 
 dense_6 (Dense)             (None, 20)                620       
                                                                 
 dense_7 (Dense)             (None, 10)                210       
                                                                 
 dense_8 (Dense)             (None, 1)                 11        
                                                                 
Total params: 4,081
Trainable params: 4,081
Non-trainable params: 0
_________________________________________________________________


In [179]:
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics= ['accuracy'])

In [180]:
nn.fit(
    income_attributes_train,
    income_target_train,
    epochs = 99,
    batch_size =len(income_attributes_train)
)

Epoch 1/99
1/1 [==============================] - 1s 927ms/step - loss: 161.6256 - accuracy: 0.7607
Epoch 2/99
1/1 [==============================] - 0s 66ms/step - loss: 152.9873 - accuracy: 0.7607
Epoch 3/99
1/1 [==============================] - 0s 62ms/step - loss: 144.4439 - accuracy: 0.7607
Epoch 4/99
1/1 [==============================] - 0s 60ms/step - loss: 137.2013 - accuracy: 0.7607
Epoch 5/99
1/1 [==============================] - 0s 59ms/step - loss: 131.2139 - accuracy: 0.7607
Epoch 6/99
1/1 [==============================] - 0s 53ms/step - loss: 125.0353 - accuracy: 0.7607
Epoch 7/99
1/1 [==============================] - 0s 54ms/step - loss: 118.7835 - accuracy: 0.7607
Epoch 8/99
1/1 [==============================] - 0s 44ms/step - loss: 112.5154 - accuracy: 0.7607
Epoch 9/99
1/1 [==============================] - 0s 52ms/step - loss: 106.2634 - accuracy: 0.7607
Epoch 10/99
1/1 [==============================] - 0s 50ms/step - loss: 100.0477 - accuracy: 0.7607
Epoch 11